Meteor.subscribe 'People'
Meteor.subscribe 'Transactions'
Meteor.subscribe 'Projects'
Meteor.subscribe 'Verifications'
Meteor.subscribe 'Actions'
Meteor.subscribe 'Shares'
Meteor.subscribe 'Messages'
Meteor.subscribe 'Organisations'
